Resources/docs/ClientSetup.md
Resources/docs/TopicSetup.md

- Topic Handler: fixed broadcast() function in onSubscribe() and onUnSubscribe() methods
- Documentation: small update to help newcomers

Topic handler bugfix and documentation update

---

Client/Authenticator/AuthenticatorInterface.php
Client/Authenticator/SessionAuthenticator.php
Client/ClientStorage.php
Client/ClientStorageInterface.php
DependencyInjection/GosWebSocketExtension.php
Event/ClientEventListener.php
Resources/config/services/services.yml
Resources/docs/SessionSetup.md
Server/App/WampApplication.php

client storage improvement

---

Client/ClientStorage.php
Command/WebsocketServerCommand.php
Resources/config/services/services.yml
Router/WampRouter.php
Server/App/WampApplication.php
Server/Type/WebSocketServer.php

Introduce null logger in order to avoid to check if time if the logger is not null to simplify the readibility of code.

Null logger instead of check if not null

---

.gitignore
Event/ClientEventListener.php
Event/ServerEvent.php
Event/StartServerListener.php
Resources/config/services/services.yml
Server/App/Registry/OriginRegistry.php
Server/App/Registry/RpcRegistry.php
Server/App/Registry/ServerRegistry.php
Server/App/Registry/TopicRegistry.php
Server/Type/WebSocketServer.php
composer.json

- Close gracefully the server via CTRL+C (SIGINT & SIGINT)
- Use stackPHP philosophy for server layer

PNTCL signal handler and Stack server component

---

Resources/config/services/services.yml
Resources/docs/TopicSetup.md
Server/App/Dispatcher/TopicDispatcher.php
Server/App/Stack/WampConnectionPeriodicTimer.php
Server/App/Stack/WampPeriodicTimer.php
Server/Type/WebSocketServer.php
Topic/ConnectionPeriodicTimer.php
Topic/TopicPeriodicTimer.php
Topic/TopicPeriodicTimerInterface.php
Topic/TopicPeriodicTimerTrait.php

Add periodic timer from topic #27

---

Server/App/WampApplication.php

Automatically call onSubscribe method of all subscribed topic when connection is closed by client

Auto unsubscribe when connection is closed by client 

---

DataCollector/PusherDecorator.php
DataCollector/WebsocketDataCollector.php
DependencyInjection/CompilerPass/DataCollectorCompilerPass.php
GosWebSocketBundle.php
Pusher/Amqp/AmqpPusher.php
Pusher/Amqp/AmqpServerPushHandler.php
Pusher/Zmq/ZmqServerPushHandler.php
Resources/config/services/services.yml
Resources/views/Collector/websocket.html.twig

Web profiler

---

Resources/docs/TopicSetup.md

Next typo & code style - TopicSetup

---

Server/App/Dispatcher/TopicDispatcher.php

If there isn't a `$topic` provided we don't need to enter the foreach loop.

Adjust order of operations

---

Resources/views/Collector/websocket.html.twig

Adds support for the redesigned web profiler in Symfony 2.8.

Support Symfony 2.8 debug toolbar markup

---

Topic/PushableTopicInterface.php

Doc block is missing the first param

Update PushableTopicInterface::onPush docblock

---

Event/StartServerListener.php

Remove double Ctrl-C requirement

---

DependencyInjection/CompilerPass/PingableDriverCompilerPass.php

Ref #170 
Anyone who has the error "The service alias "gos_web_socket.session_handler" does not exist." can confirm this patch is ok?

fix getAlias not found

---

Resources/docs/Ssl.md

Adds more description for SSL configuration with stunnel.

Update SSL documentation

---

Server/App/Dispatcher/TopicDispatcher.php

https://github.com/GeniusesOfSymfony/WebSocketBundle/issues/227

#227 repeat fix detecting push method

---

Resources/docs/ConfigurationReference.md
Resources/docs/TopicSetup.md

Port and host examples mixed up

Improved documentation

---

Resources/config/services/services.yml

Since this is an abstract template, make the service abstract.

Make abstract pusher an abstract service

---

DependencyInjection/Configuration.php
Pusher/Zmq/ZmqPusher.php

This is critical improvement for us project.

Add linger param to zmq pusher

---

Event/ClientEventListener.php

I overridde gos_web_socket.websocket_authentification.provider via CompilerPass Definition

Ability to inject custom AuthenticationProvider

---

Resources/config/services/services.yml
Resources/views/Collector/websocket.html.twig

symfony flex toolbar collector fix

symfony 4 toolbar collector support

---

Resources/config/services/services.yml
Topic/TopicManager.php

WampApplication is now passed by setter instead of constructor

Removed circural reference

---

Client/Driver/SymfonyCacheDriverDecorator.php
Resources/config/services/services.yml
Resources/docs/SessionSetup.md
composer.json

Adds native support for the Symfony Cache component as a client storage driver decorator

Add decorator for symfony/cache

---

Pusher/Amqp/AmqpPusher.php
Pusher/Wamp/WampPusher.php
Pusher/Zmq/ZmqPusher.php

Just fixes the interface implementation.

Add missing return types to Pusher classes

---

Resources/docs/SessionSetup.md

Name session in Ratchet load from php.ini in Symfony can change [ session name  ](https://symfony.com/doc/current/reference/configuration/framework.html#name)
https://github.com/ratchetphp/Ratchet/blob/b85c2a1f189e43f7f0861daf7ff81d016c5d6403/src/Ratchet/Session/Storage/Proxy/VirtualProxy.php#L23

Documentation update
