Command/WebsocketServerCommand.php
Resources/config/services/services.yml
Server/EntryPoint.php
Server/Type/ServerInterface.php
Server/Type/WebSocketServer.php

```cmd
php app/console gos:websocket:server -p 1337
php app/console gos:websocket:server -a 192.168.1.4 -p 1338
php app/console gos:websocket:server -p 1339
```

Allow to load balance websocket

---

Client/Driver/PredisDriver.php
DependencyInjection/Configuration.php
DependencyInjection/GosWebSocketExtension.php
Resources/docs/SessionSetup.md

I think that is useful feature, when use redis to storage client, can set prefix for key. For example instead key 1, exist key YOUR_PREFIX:1. I think it is a small duplication protection to keys from other parts of the application that uses redis, and increases transparency. 
Should not affect to the other storage, but please re-test it.

[feature] possible use prefix on redis client storage

---

DependencyInjection/Configuration.php
Resources/docs/Pusher.md

The ``\AMQP_Connection`` object accepts an array with credentials, however the key used for username is defined as 'login'. (https://github.com/pdezwart/php-amqp/blob/master/amqp_connection.c#L267) This will not result in an error necessarily, but only when you configure an username other then 'guest'.
* Changed 'amqp' ``Configuration`` node 'username' to 'login'
* Modified Pusher documentation to match change in ``Configuration``

[Fix] AMQP_Connection doesn't accept key 'username' as configuration

---

Topic/TopicPeriodicTimer.php

Events in a `TopicPeriodicTimerInterface` object's `registerPeriodicTimer` method do not get cancelled at all because of this check being backward.  Short code snippet showing how I ran into it:
```php
if (!$this->periodicTimer->isPeriodicTimerActive($this, 'myEvent')) {
// This only runs in certain conditions
if ($conditionIsTrue) {
$this->periodicTimer->addPeriodicTimer($this, 'myEvent', 15, function() use ($topic) {
// Some condition to cancel the timer
if ($shouldCancelTimer) {
$this->periodicTimer->cancelPeriodicTimer($this, 'myEvent');
return;
}
// Other code that runs if we don't cancel the event
});
}
}
```

Periodic timer events do not cancel

---

DependencyInjection/CompilerPass/LoopFactoryCompilerPass.php
GosWebSocketBundle.php
Resources/config/services/services.yml
Server/Type/WebSocketServer.php
Topic/TopicPeriodicTimer.php
composer.json

It works with Symfony `^3.0` but I don't really like this line in composer file : 
`"gos/pubsub-router-bundle": "dev-sf3"`
Maybe create a branch-alias in [gos/pubsub-router-bundle](https://github.com/GeniusesOfSymfony/PubSubRouterBundle/tree/sf3) or a tag version.

SF3 : Fix dependency and services contructor

---

Pusher/Wamp/WampPusher.php
Resources/config/services/services.yml

In the WAMP pusher, the `@gos_web_socket.push_message.serializer` service gets injected through both the constructor and a method call defined by the parent `@gos_web_socket.abstract.pusher` service.  The constructor injection is therefore duplicated code and can be removed.

Don't need to inject Serializer twice

---

DependencyInjection/Configuration.php
DependencyInjection/GosWebSocketExtension.php
Resources/docs/ConfigurationReference.md
Tests/DependencyInjection/ConfigurationTest.php
composer.json
phpunit.xml.dist

Hello
In my case I use the "-" character for token separator. This PR allow to choose another token separator than the default "/". The slash remain the default separator. This parameter is optional.

Allow to change the token separator from the configuration

---

Event/StartServerListener.php

The `$siginfo` variable is currently undefined, pressing `CTRL-C` causes a notice in the console for this.
Also corrected the spelling of CTRL.

Undefined variable siginfo, spelling fixes

---

Client/Driver/DoctrineCacheDriverDecorator.php

Allow any object implementing Doctrine's `Cache` interface instead of restricting to classes extending the abstract `CacheProvider`.

Typehint the Doctrine Cache interface instead of the CacheProvider class

---

DependencyInjection/CompilerPass/PingableDriverCompilerPass.php

Tested on Symfony 2.8+
When a ``session_handler`` is configured, the ``PingableDriverCompilerPass`` try to get the service alias ``gos_web_socket.session_handler``. It returns the error ``ReflectionException in ContainerBuilder.php line 929: Class does not exist``.
The fix replaces ``get()`` by ``getAlias``, and works.
Also fix #134

try to find alias to fix "Class not found"

---

Server/App/Dispatcher/TopicDispatcherInterface.php

Fixes this:
PHP Fatal error:  Declaration of GosBundleWebSocketBundleServerAppDispatcherTopicDispatcher_000000003523c6a7000000005918c023030ddf746fbe22dfac87e52212494d92::dispatch($calledMethod, Ratchet\ConnectionInterface $conn,  
Ratchet\Wamp\Topic $topic, Gos\Bundle\WebSocketBundle\Router\WampRequest $request, $payload = NULL, $exclude = NULL, $eligible = NULL, $provider = NULL) must be compatible with Gos\Bundle\WebSocketBundle\Server\App\  
Dispatcher\TopicDispatcherInterface::dispatch($calledMethod, ?Ratchet\ConnectionInterface $conn, Ratchet\Wamp\Topic $topic, Gos\Bundle\WebSocketBundle\Router\WampRequest $request, $payload = NULL, $exclude = NULL, $e  
ligible = NULL)

make compatible with php 7.1

---

DependencyInjection/Configuration.php
DependencyInjection/GosWebSocketExtension.php

Imho, it's more relevant to set a scalar node instead of a boolean node because it allows us to put a DIC parameter.
Indeed, the ssl should depend on the environment, and for this value, we would not override it in another configuration file.

Allow to use a parameter

---

composer.json

Bump the pubsub router bundle dependency to the 0.3 tag.  Since Composer handles 0.x in a "special" way, I can't think of another way to bump this without having a `0.*` type of constraint which isn't optimal when you don't have a 1.0 release yet.

Bump pubsub dependency to 0.3

---

README.md
Resources/docs/ClientSetup.md
Resources/docs/Events.md
Resources/docs/PeriodicSetup.md
Resources/docs/RPCSetup.md
Resources/docs/SessionSetup.md
Resources/docs/ShipInProduction.md
Resources/docs/Ssl.md
Resources/docs/TopicSetup.md
Resources/docs/code/SharingConfig.md

GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1

Fix broken headings in Markdown files

---

Resources/docs/SessionSetup.md

There is a "bug" in the documentation and if you have defined a firewall context it does not work.
Here more information https://github.com/GeniusesOfSymfony/WebSocketBundle/issues/136

Note about firewall configuration

---

Server/App/WampApplication.php

Use debug verbosity level debug instead of info when publishing. It pollutes your log when sending huge amount of messages per minute.

Change verbosity level onPublish

---

DataCollector/WebsocketDataCollector.php

Since Symfony 3.4 classes implementing DataCollectorInterface should implement reset() method.

Implement reset method in WebsocketDataCollector

---

Resources/docs/TopicSetup.md
Server/App/Dispatcher/TopicDispatcher.php
Server/Exception/FirewallRejectionException.php
Topic/FirewalledTopicInterface.php
Topic/SecuredTopicInterface.php

I added a new interface, `FirewalledTopicInterface`, that allows adding logic inside user's topic service to close unwanted connections.
I extended the current TopicDispatcher to handle this type of topic service. 
Modifications are pretty strightforward, the only issue is that:
- IF a client connects to more than one topic
- AND one of them fails
- the connection is closed, disconnecting from ALL topics
I do not know if this is the correct behaviour, it is a conservative approach though.

Added firewalled topic

---

.travis.yml
Event/ClientRejectedEvent.php
Event/StartServerListener.php
Resources/config/services/services.yml
Server/App/Dispatcher/TopicDispatcher.php
Server/App/Stack/OriginCheck.php
Server/App/WampApplication.php
Server/Type/WebSocketServer.php
Server/WampServer.php
Topic/TopicManager.php
composer.json
phpunit.xml

After a small refactor I have managed to eliminate the `gos/ratchet` and `gos/ratchet-stack` (thanks to the PSR7 ) dependencies and now I'm using the latest  **Ratchet** and **ReactPHP** versions.
I am using the new branch in dev and prod environment for 3 days and it works fine. The applications pass all test (acceptance and load) successfully and there are not reported issues.
I think that the code is ready to be merged and to be released a "2.0" WebSocketBundle version.
Here information about installed packages:
```
cboden/ratchet 		=> v0.4.1                    
react/cache 		=> v0.4.2                    
react/dns 		=> v0.4.12                   
react/event-loop	=> v0.4.3                    
react/promise		=> v2.5.1                    
react/promise-timer	=> v1.2.1 …
```

Refactor/ratchet 0.4 support

---

DependencyInjection/CompilerPass/PingableDriverCompilerPass.php
Resources/docs/SessionSetup.md

Database session can't be defined like recommended in http://symfony.com/doc/current/doctrine/pdo_session_storage.html
Constructing service "doctrine.dbal.default_connection" from a parent definition is not supported at build time.

[#280] Do not instantiate PDOSessionHandler at build time

---

DependencyInjection/CompilerPass/PingableDriverCompilerPass.php

I'm sorry, I made a mistake in my previous fix; ignoring when PdoSessionHandler is used and not a child of this class.

restore Pdo periodic ping

---

Client/DoctrineCacheDriverDecorator.php
Client/DriverInterface.php

There are duplicate classes for the Doctrine cache decorator and the driver interface.  Deprecate them and point to the actual class/interface used by the bundle.

Deprecate duplicate classes

---

Event/StartServerListener.php
Server/App/Stack/WampConnectionPeriodicTimer.php
Topic/ConnectionPeriodicTimer.php
Topic/TopicPeriodicTimer.php
composer.json

There were a few B/C breaks in the react/event-loop 0.5 release affecting this bundle.  They are accounted for with this PR.

Update react/event-loop dependency to 1.0

---

DependencyInjection/GosWebSocketExtension.php

With 2.0 [requiring Symfony 3.4 or later](https://github.com/GeniusesOfSymfony/WebSocketBundle/pull/348), the bundle's configuration can take advantage of auto configuring services for improved DX and that makes allowing the configuration of these service types through both the bundle's configuration tree and through service tags redundant.  Therefore, this PR deprecates these configuration nodes on the 1.x branch to be removed in 2.0.

[1.x] Deprecate using the config to add services to RPC, topic, server, and periodic registries in favor of service tagging and compiler passes

---

Client/Auth/WebsocketAuthenticationProvider.php
Client/ClientManipulator.php
Client/ClientManipulatorInterface.php
Client/ClientStorage.php
Client/ClientStorageInterface.php
Event/ClientEventListener.php
Resources/config/services/services.yml
Resources/docs/SessionSetup.md
Tests/Client/Auth/WebsocketAuthenticationProviderTest.php
Tests/Client/ClientManipulatorTest.php
Tests/Client/ClientStorageTest.php
Tests/Event/ClientEventListenerTest.php
UPGRADE-2.0.md

This changes the client storage layer to store the `Symfony\Component\Security\Core\Authentication\Token\TokenInterface` object that is read out of the session when processing a client connection versus storing whatever user implementation the token is wrapping.  This also has a couple of other mild UX tweaks.
The `WebsocketAuthenticationProvider` right now authenticates a token then replaces whatever token is in the `@security.token_storage` service.  With the websocket server being a single long running backend process, this is woefully inefficient and can cause some unexpected behavior if you try to use the `@security.authorization_checker` service for any type of access checks (i.e. if your topic implements `Gos\Bundle\WebSocketBundle\Topic\SecuredTopicInterface`).  So it has been …

[2.0] Refactor client storage to save the token from the session versus the user it represents

---

DependencyInjection/Configuration.php
DependencyInjection/GosWebSocketExtension.php
Resources/config/services/services.yml
Server/App/ServerBuilder.php
Tests/DependencyInjection/ConfigurationTest.php
Tests/Server/App/ServerBuilderTest.php

In Ratchet 0.4, support was added for a keepalive function in the `WsServer` class.  This PR adds support for enabling it through the bundle config.  Added is:
- A new configuration node to enable the keepalive ping
- A new configuration node to specify the ping interval (in seconds)
- Relevant code in the server builder to enable the feature at runtime
To enable, update the bundle config:
```yaml
gos_web_socket:
server:
keepalive_ping: true
keepalive_interval: 30 #time in seconds between pings, defaults to 30
```

[2.0] Enable support for the WsServer keepalive feature

---

Resources/docs/ClientSetup.md

GosSocket.unsubscribeToChannel should be GosSocket.unsubscribeFromChannel. Minor typo in docs that had me confused for a moment.

Fix typo in docs
